ExUnit.configure(exclude: [:integration, :load, :nats_live])
ExUnit.start()

Code.require_file("support/fake_party_repo.ex", __DIR__)
Code.require_file("support/postgres_helper.ex", __DIR__)

Mox.defmock(BotArmyRpg.CharacterStoreMock, for: BotArmyRpg.CharacterStoreBehaviour)
Mox.defmock(BotArmyRpg.SessionStoreMock, for: BotArmyRpg.SessionStoreBehaviour)
Mox.defmock(BotArmyRpg.SceneFactStoreMock, for: BotArmyRpg.SceneFactStoreBehaviour)
Mox.defmock(BotArmyRpg.ThemeStoreMock, for: BotArmyRpg.ThemeStoreBehaviour)
Mox.defmock(BotArmyRpg.PartyStoreMock, for: BotArmyRpg.PartyStoreBehaviour)
Mox.defmock(BotArmyRpg.CampaignStoreMock, for: BotArmyRpg.CampaignStoreBehaviour)
Mox.defmock(BotArmyRpg.XpEventStoreMock, for: BotArmyRpg.XpEventStoreBehaviour)
Mox.defmock(BotArmyRpg.CampaignRosterStoreMock, for: BotArmyRpg.CampaignRosterStoreBehaviour)
Mox.defmock(BotArmyRpg.QuestStoreMock, for: BotArmyRpg.QuestStoreBehaviour)
