defmodule BotArmyRpg.SceneFactStoreTest do
  use ExUnit.Case
  @moduletag :stores

  alias BotArmyRpg.SceneFactStore

  describe "the wire shape of a stored fact" do
    # Every other test of this store mocks it, so this conversion — the only thing
    # between the database and every reader of a turn — had no test at all. It shipped
    # `"2026-10-08T00:46:52"`, which names no zone, and the dashboard's
    # `DateTime.from_iso8601/1` refuses that outright (`{:error, :missing_offset}`), so
    # every turn there drew no time at all.
    defp stored(at) do
      %BotArmyRpg.Schemas.SceneFact{
        id: "11111111-1111-1111-1111-111111111111",
        tenant_id: "00000000-0000-0000-0000-000000000001",
        user_id: nil,
        session_id: "22222222-2222-2222-2222-222222222222",
        content: "the fire has burned down to embers",
        category: "observation",
        source: "gm",
        inserted_at: at,
        updated_at: at
      }
    end

    test "a stored fact says which zone its time is in" do
      at = ~N[2026-10-08 00:46:52]
      fact = SceneFactStore.schema_to_map(stored(at))

      assert fact["created_at"] == "2026-10-08T00:46:52Z"
      assert fact["updated_at"] == "2026-10-08T00:46:52Z"
    end

    test "a reader that parses ISO-8601 can read the time back" do
      fact = SceneFactStore.schema_to_map(stored(~N[2026-10-08 00:46:52]))

      assert {:ok, then, _offset} = DateTime.from_iso8601(fact["created_at"])
      assert DateTime.to_naive(then) == ~N[2026-10-08 00:46:52]

      # The zone-less form is what broke it. Pin that it is not that.
      assert {:error, :missing_offset} = DateTime.from_iso8601("2026-10-08T00:46:52")
    end

    test "the time is the UTC the store actually wrote, not a local clock" do
      # `timestamps()` is Ecto's `:naive_datetime`, autogenerated with
      # `NaiveDateTime.utc_now/0` — so a fact written now reads back as now-in-UTC.
      now = NaiveDateTime.utc_now()
      fact = SceneFactStore.schema_to_map(stored(now))

      assert {:ok, then, 0} = DateTime.from_iso8601(fact["created_at"])
      assert_in_delta DateTime.diff(DateTime.utc_now(), then, :second), 0, 5
    end
  end

  describe "story?/1" do
    test "a turn someone in the scene spoke is story" do
      assert SceneFactStore.story?(%{"source" => "operator", "content" => "Hi!"})
      assert SceneFactStore.story?(%{"source" => "gm", "content" => "the GM closed the door"})
    end

    test "the machinery speaking is not story, whatever it says" do
      refute SceneFactStore.story?(%{"source" => "system", "content" => "the day advanced"})
    end

    test "a note that declares itself a check is not story, whoever wrote it" do
      refute SceneFactStore.story?(%{
               "source" => "operator",
               "content" => "[verification] M1: a turn moves the window clock"
             })
    end

    test "a note is recognised through leading whitespace and shouting" do
      refute SceneFactStore.story?(%{"source" => "gm", "content" => "  [verification] x"})
      refute SceneFactStore.story?(%{"source" => "gm", "content" => "[VERIFICATION] x"})
    end

    test "the word elsewhere in a turn does not make the turn a note" do
      assert SceneFactStore.story?(%{
               "source" => "operator",
               "content" => "my [verification] came back green"
             })
    end

    test "a fact without a content is not a note" do
      assert SceneFactStore.story?(%{"source" => "gm"})
    end
  end

  describe "select_recent/3" do
    @tenant "00000000-0000-0000-0000-000000000099"
    @user "00000000-0000-0000-0000-0000000000aa"
    @here "00000000-0000-0000-0000-0000000000cc"
    @earlier "00000000-0000-0000-0000-0000000000bb"

    defp fact(content, source, at, session \\ @earlier) do
      %{
        "content" => content,
        "source" => source,
        "session_id" => session,
        "tenant_id" => @tenant,
        "user_id" => @user,
        "created_at" => at
      }
    end

    # The newest two facts are notes, so a selection that filtered *after* the
    # limit would answer one turn and one note-or-nothing; the newest two *turns*
    # are what a caller asked for.
    defp facts_with_newest_two_notes do
      [
        fact("the oldest turn", "operator", "2026-05-10T09:00:00"),
        fact("[verification] the middle note", "system", "2026-05-10T10:00:00"),
        fact("a turn from yesterday", "gm", "2026-05-10T11:00:00"),
        fact("[verification] the newest note", "operator", "2026-05-10T12:00:00")
      ]
    end

    test "answers newest first, this identity's, without this window's own turns" do
      facts =
        facts_with_newest_two_notes() ++
          [fact("this window's own turn", "operator", "2026-05-10T13:00:00", @here)] ++
          [
            %{
              fact("another household's turn", "operator", "2026-05-10T14:00:00")
              | "user_id" => "someone-else"
            }
          ]

      selected =
        SceneFactStore.select_recent(facts, @tenant,
          exclude_session_id: @here,
          user_id: @user,
          limit: 10
        )

      assert Enum.map(selected, & &1["content"]) == [
               "[verification] the newest note",
               "a turn from yesterday",
               "[verification] the middle note",
               "the oldest turn"
             ]
    end

    test "story_only drops every note" do
      selected =
        SceneFactStore.select_recent(facts_with_newest_two_notes(), @tenant,
          user_id: @user,
          story_only: true,
          limit: 10
        )

      assert Enum.map(selected, & &1["content"]) == [
               "a turn from yesterday",
               "the oldest turn"
             ]
    end

    test "story_only drops the notes before the limit, so the limit counts turns" do
      selected =
        SceneFactStore.select_recent(facts_with_newest_two_notes(), @tenant,
          user_id: @user,
          story_only: true,
          limit: 2
        )

      assert Enum.map(selected, & &1["content"]) == [
               "a turn from yesterday",
               "the oldest turn"
             ]
    end

    test "a window whose newest facts are all notes carries nothing, not a note" do
      facts = [
        fact("[verification] one", "system", "2026-05-10T11:00:00"),
        fact("[verification] two", "operator", "2026-05-10T12:00:00")
      ]

      assert SceneFactStore.select_recent(facts, @tenant, user_id: @user, story_only: true) == []
    end
  end
end
