defmodule BotArmyRpg.Themes.Renderer do
  @moduledoc """
  Render a theme map as Elixir source code for a `BotArmyRpg.Themes.Preset`
  module.

  The output is intentionally hand-edit-friendly:

    * One section per key (`vocabulary`, `templates`, `npc_personas`, `rules`)
      so a human reviewer can edit a single section without scrolling.
    * Maps are key-sorted to keep diffs stable across regenerations.
    * Long strings stay on a single line — Elixir's standard formatter will
      wrap them after `mix format`.

  This module never writes to disk; callers (typically `Mix.Tasks.Rpg.DraftTheme`)
  decide where the output lands.
  """

  @action_verbs ~w(attack defend buff inspire inspect negotiate hack evade skill move)

  @doc """
  Render the given `theme_map` as an Elixir source string for a preset
  module named under `BotArmyRpg.Themes.<Suffix>`.

  ## Options

    * `:source` — string describing where the theme came from (file path,
      URL, etc.). Embedded in the `@moduledoc` for traceability.
    * `:warnings` — list of strings to surface in the moduledoc so reviewers
      see what the extractor was unsure about.
  """
  def render(name, theme_map, opts \\ []) when is_binary(name) and is_map(theme_map) do
    suffix = camelcase(name)
    display = Map.get(theme_map, "setting", titlecase(name))

    source_note = opts[:source] && "  Source: #{opts[:source]}\n"
    warnings_block = format_warnings(opts[:warnings] || [])

    moduledoc = """
      DRAFT theme preset generated by `mix rpg.draft_theme`.
    #{source_note || ""}#{warnings_block}
      Review and edit the placeholder values before flipping this preset
      live. Mechanics default to the d20 chassis; declare
      `rules.resolution.success_bands` to use a different chassis.
    """

    rules = Map.get(theme_map, "rules", %{"action_types" => @action_verbs})

    """
    defmodule BotArmyRpg.Themes.#{suffix} do
      @moduledoc \"\"\"
      #{display} theme preset.

    #{indent(moduledoc, "  ")}\"\"\"

      use BotArmyRpg.Themes.Preset

      @impl true
      def name, do: "#{name}"

      @impl true
      def display_name, do: "#{escape_string(display)}"

      @impl true
      def description do
        "#{escape_string(Map.get(theme_map, "tone", "TODO"))}"
      end

      @impl true
      def theme do
        %{
          "setting" => "#{escape_string(Map.get(theme_map, "setting", "TODO"))}",
          "tone" => "#{escape_string(Map.get(theme_map, "tone", "TODO"))}",
          "mechanic" => "#{escape_string(Map.get(theme_map, "mechanic", "TODO"))}",
          "vocabulary" => vocabulary(),
          "templates" => templates(),
          "npc_personas" => npc_personas(),
          "rules" => rules()
        }
      end

      defp vocabulary do
    #{render_map(Map.get(theme_map, "vocabulary", %{}), 4)}
      end

      defp templates do
    #{render_map(Map.get(theme_map, "templates", %{}), 4)}
      end

      defp npc_personas do
    #{render_personas(Map.get(theme_map, "npc_personas", %{}), 4)}
      end

      defp rules do
    #{render_rules(rules, 4)}
      end
    end
    """
  end

  defp render_map(map, indent_cols) when map_size(map) == 0 do
    pad = String.duplicate(" ", indent_cols)
    "#{pad}%{}"
  end

  defp render_map(map, indent_cols) do
    pad = String.duplicate(" ", indent_cols)
    inner_pad = String.duplicate(" ", indent_cols + 2)

    entries =
      map
      |> Enum.sort_by(fn {k, _} -> to_string(k) end)
      |> Enum.map_join(",\n", fn {k, v} ->
        "#{inner_pad}\"#{escape_string(to_string(k))}\" => \"#{escape_string(to_string(v))}\""
      end)

    "#{pad}%{\n#{entries}\n#{pad}}"
  end

  defp render_personas(map, indent_cols) when map_size(map) == 0 do
    pad = String.duplicate(" ", indent_cols)
    "#{pad}%{}"
  end

  defp render_personas(map, indent_cols) do
    pad = String.duplicate(" ", indent_cols)
    inner_pad = String.duplicate(" ", indent_cols + 2)

    entries =
      map
      |> Enum.sort_by(fn {k, _} -> to_string(k) end)
      |> Enum.map_join(",\n", fn {k, persona} ->
        "#{inner_pad}\"#{escape_string(to_string(k))}\" => #{render_persona(persona, indent_cols + 2)}"
      end)

    "#{pad}%{\n#{entries}\n#{pad}}"
  end

  defp render_persona(persona, indent_cols) do
    inner_pad = String.duplicate(" ", indent_cols + 2)

    title = persona["title"] || "TODO"
    demeanor = persona["demeanor"] || "TODO"
    carries = persona["carries"] || []
    assignments = persona["bot_assignments"] || []

    """
    %{
    #{inner_pad}"title" => "#{escape_string(title)}",
    #{inner_pad}"demeanor" => "#{escape_string(demeanor)}",
    #{inner_pad}"carries" => #{render_list(carries)},
    #{inner_pad}"bot_assignments" => #{render_list(assignments)}
    #{String.duplicate(" ", indent_cols)}}\
    """
  end

  defp render_list([]), do: "[]"

  defp render_list(items) do
    rendered =
      items
      |> Enum.map_join(", ", fn item -> "\"#{escape_string(to_string(item))}\"" end)

    "[#{rendered}]"
  end

  defp render_rules(rules, indent_cols) when is_map(rules) do
    pad = String.duplicate(" ", indent_cols)
    inner_pad = String.duplicate(" ", indent_cols + 2)
    action_types = Map.get(rules, "action_types", @action_verbs)

    action_lines =
      action_types
      |> Enum.map_join(",\n", fn a -> "#{inner_pad}  \"#{escape_string(to_string(a))}\"" end)

    base = """
    #{pad}%{
    #{inner_pad}"action_types" => [
    #{action_lines}
    #{inner_pad}]
    #{pad}}\
    """

    case Map.get(rules, "resolution") do
      nil ->
        base

      _resolution ->
        # If extractor ever populates this we still render reasonably, but
        # the v1 contract leaves resolution empty so humans pick the chassis.
        base
    end
  end

  defp escape_string(nil), do: ""

  defp escape_string(str) when is_binary(str) do
    str
    |> String.replace("\\", "\\\\")
    |> String.replace("\"", "\\\"")
    |> String.replace("\n", "\\n")
  end

  defp escape_string(other), do: escape_string(to_string(other))

  defp titlecase(name) do
    name
    |> String.split("_")
    |> Enum.map_join(" ", &String.capitalize/1)
  end

  defp camelcase(name) do
    name
    |> String.split("_")
    |> Enum.map_join("", &String.capitalize/1)
  end

  defp indent(text, pad) do
    text
    |> String.split("\n")
    |> Enum.map_join("\n", fn line ->
      if line == "", do: "", else: pad <> line
    end)
  end

  defp format_warnings([]), do: ""

  defp format_warnings(warnings) do
    bullets = Enum.map_join(warnings, "\n  ", fn w -> "  * #{w}" end)
    "  Extractor warnings:\n#{bullets}\n"
  end
end
